export const commonExifProps = [
  'Make', 'Model', 'LensModel', 'FNumber', 'ISO',
  'FocalLength', 'Flash', 'MeteringMode', 'ExposureProgram',
  'WhiteBalance', 'ExposureCompensation'
];

export const exifDescriptions = {
  'Make': '相机制造商',
  'Model': '相机型号',
  'LensModel': '镜头型号',
  'DateTime': '拍摄日期和时间',
  'ExposureTime': '曝光时间',
  'FNumber': '光圈值',
  'ISO': 'ISO感光度',
  'FocalLength': '焦距',
  'ImageWidth': '图像宽度',
  'ImageHeight': '图像高度',
  'Orientation': '图像方向',
  'GPSLatitude': 'GPS纬度',
  'GPSLongitude': 'GPS经度',
  'Flash': '闪光灯状态',
  'MeteringMode': '测光模式',
  'ExposureProgram': '曝光程序',
  'WhiteBalance': '白平衡',
  'ExposureCompensation': '曝光补偿',
  'SubjectDistance': '拍摄距离',
  'DigitalZoomRatio': '数字变焦比',
  'FocalLengthIn35mmFormat': '35mm等效焦距',
  'SceneCaptureType': '场景捕获类型',
  'Contrast': '对比度',
  'Saturation': '饱和度',
  'Sharpness': '锐度',
  'DateTimeOriginal': '原始拍摄时间',
  'DateTimeDigitized': '数字化时间',
  'SubSecTime': '子秒时间',
  'SubSecTimeOriginal': '原始子秒时间',
  'SubSecTimeDigitized': '数字化子秒时间',
  'GPSAltitude': 'GPS海拔高度',
  'GPSAltitudeRef': 'GPS海拔高度参考',
  'GPSTimeStamp': 'GPS时间戳',
  'GPSDateStamp': 'GPS日期戳',
  'GPSProcessingMethod': 'GPS处理方法',
  'GPSAreaInformation': 'GPS区域信息',
  'GPSDifferential': 'GPS差分'
};
